shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
use = ['{{ name }}.zsh']

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.ohmyzsh]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins'
use = ['{dotenv,dotnet,git,gitignore,macos,npm}/*.plugin.zsh']