## Fig environment variables
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh

# Path to dotfiles repository.
export DOTFILES="$HOME/Developer/dotfiles"

# Add homebrew to PATH
eval "$(/opt/homebrew/bin/brew shellenv)"

## Fig environment variables
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh