# Fig environment variables.
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh

DISABLE_AUTO_TITLE="true"

# refresh installed completions
autoload -U compinit && compinit

# register aliases
source "$DOTFILES/shell/aliases.sh"

# load sheldon plugins
eval "$(sheldon source)"

# starship prompt
eval "$(starship init zsh)"

# Fig environment variables.
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh