# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
DISABLE_AUTO_TITLE="true"

# refresh installed completions
autoload -U compinit && compinit

# register aliases
source "$DOTFILES/shell/aliases.sh"

# load sheldon plugins
eval "$(sheldon source)"

# starship prompt
eval "$(starship init zsh)"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
